project_id = "lwklmazvdqrmuriczhws"

[functions.realtime-reservation-token]
verify_jwt = false

[functions.save-voice-reservation]
verify_jwt = false

[functions.confirm-order]
verify_jwt = false

[functions.verify-and-push-order]
verify_jwt = false

[functions.send-christmas-reservation-notification]
verify_jwt = false

[functions.send-takeaway-order]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false
